# Generated by Django 5.1.6 on 2025-02-25 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('typeofkitchen', models.TextField(verbose_name='Специфика заведения')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Рейтинг')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Cafes',
            },
        ),
        migrations.CreateModel(
            name='CulinaryClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DishCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'DishesCatalog',
            },
        ),
        migrations.CreateModel(
            name='TypeOfDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Type_of_dishes',
            },
        ),
        migrations.CreateModel(
            name='TypeOfKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CafeImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('cafe_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_images', to='core.cafemodel')),
            ],
        ),
        migrations.CreateModel(
            name='DishLibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
                ('CulinaryClassModel_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.culinaryclassmodel', verbose_name='Кулинарный класс')),
                ('cafe_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cafemodel', verbose_name='')),
                ('dishcatalog_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dishcatalog', verbose_name='Блюдо-образец для сравнения')),
                ('type_of_kitchen_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeofkitchen', verbose_name='Тип кухни')),
            ],
            options={
                'verbose_name_plural': 'LibraryDishes',
            },
        ),
        migrations.CreateModel(
            name='DishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=11)),
                ('rating2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=11)),
                ('dish_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bestdishes', to='core.dishlibrarymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='DishImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('dish_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_images', to='core.dishmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VisitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата визита')),
                ('description', models.TextField(verbose_name='Описание визита')),
                ('average_dish_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Рейтинг блюд визита')),
                ('register', models.BooleanField(default=True)),
                ('cafe_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cafemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Visits',
            },
        ),
        migrations.CreateModel(
            name='VisitImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('visit_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_images', to='core.visitmodel')),
            ],
        ),
        migrations.AddField(
            model_name='dishmodel',
            name='visit_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_dishes', to='core.visitmodel'),
        ),
    ]
