# Generated by Django 5.1.6 on 2025-03-22 17:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cafeimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=1, size=[1920, 1080], upload_to='media'),
        ),
        migrations.AlterField(
            model_name='dishimagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=1, size=[1920, 1080], upload_to='media'),
        ),
        migrations.AlterField(
            model_name='visitimagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=1, size=[1920, 1080], upload_to='media'),
        ),
    ]
