# Generated by Django 5.1.6 on 2025-05-04 14:21

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cafeimagemodel_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitmodel',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='cafeimagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=1, size=[1920, 1080], upload_to='media/cafes/%Y.%m.%d'),
        ),
        migrations.AlterField(
            model_name='dishimagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=1, size=[1920, 1080], upload_to='media/dishes/%Y.%m.%d'),
        ),
        migrations.AlterField(
            model_name='visitimagemodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=1, size=[1920, 1080], upload_to='media/visits/%Y.%m.%d'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
