"""
Django settings for foodster project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os

# from cms.test_utils.project.pluginapp.plugins.style.models import Style

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4(@m-8td(7q+m-jjzakz5+1ea6gk#ng@i-rt3&_8wu^3749lo7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"  # По умолчанию True (для разработки)

if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = ['critifood.ru','92.255.77.160']

if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': '/var/log/django/errors.log',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'ERROR',
                'propagate': True,
            },
        },
    }

X_FRAME_OPTIONS = 'SAMEORIGIN'



# Application definition

INSTALLED_APPS = [
    # 'djangocms_admin_style',

    # 'admin_interface',
    # 'colorfield',

    # 'dal',
    # 'dal_select2',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # 'iommi',
    'django_bootstrap5',
    'django_tables2',
    # 'crudbuilder',
    'django_filters',
    # 'django_select2',
    # 'debug_toolbar',
    # 'django_addanother',
    'services',
    'system.apps.SystemConfig',

    # 'rating.apps.RatingConfig',

    'cms',
    'menus',
    'treebeard',
    'sekizai',
    # 'djangocms_forms',
    # 'crispy_forms',
    # 'crispy_bootstrap5',
    # 'foodster',
    # 'django_starfield.apps.DjangoStarfieldConfig',
    # 'django_selectize',

    # 'inline_ordering',
    'filer',
    'easy_thumbnails',

    # 'photologue',
    'sortedm2m',

    # My frontend plugins
    # 'light_gallery',
    # 'djangocms_parallaxjs',
    # 'djangocms_unitegallery',
    # 'djangocms_cameraslider',
    # 'djangocms_slick_slider.apps.DjangocmsSlickSliderConfig',
    # 'cmsplugin_gallery',
    # 'sorl.thumbnail',
    # 'djangocms_slider',
    # 'djangocms_thumbnail_slider',
    # the default CKEditor - optional, b        `sed in most projects
    'djangocms_text_ckeditor',

    # some content plugins - optional, but used in most projects
    # 'djangocms_file',
    # 'djangocms_icon',
    # 'djangocms_picture',
    # 'djangocms_style',
    # 'djangocms_googlemap',
    # 'djangocms_video',

    # optional django CMS Frontend modules
    'djangocms_frontend',
    'djangocms_frontend.contrib.accordion',
    'djangocms_frontend.contrib.alert',
    'djangocms_frontend.contrib.badge',
    'djangocms_frontend.contrib.card',
    'djangocms_frontend.contrib.carousel',
    'djangocms_frontend.contrib.collapse',
    'djangocms_frontend.contrib.content',
    'djangocms_frontend.contrib.grid',
    'djangocms_frontend.contrib.jumbotron',
    'djangocms_frontend.contrib.link',
    'djangocms_frontend.contrib.listgroup',
    'djangocms_frontend.contrib.media',
    'djangocms_frontend.contrib.image',
    'djangocms_frontend.contrib.tabs',
    'djangocms_frontend.contrib.utilities',

    'django_htmx',
    'foodster',
    'formset',
    'django_resized',
    # 'radio_formset',
    # 'gallery',

    'core',
    'location_field.apps.DefaultConfig',

    # 'cafes_cms_integration.apps.CafesCmsIntegrationConfig',

    ]

MIDDLEWARE = [
    # 'iommi.live_edit.Middleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',

    'django_htmx.middleware.HtmxMiddleware',
    # 'iommi.sql_trace.Middleware',
    # 'iommi.profiling.Middleware',

    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',

    # 'iommi.middleware',

    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

ROOT_URLCONF = 'foodster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'django.template.context_processors.i18n',

                'cms.context_processors.cms_settings',
                'sekizai.context_processors.sekizai',
                'core.context_processors.site_settings',

            ],
        },
    },
]

LOCATION_FIELD = {
    'provider.openstreetmap.max_zoom': 18,
    # 'map.provider': 'yandex',
    # 'map.zoom': 13,
    # 'search.provider': 'yandex',
}

WSGI_APPLICATION = 'foodster.wsgi.application'

CMS_TEMPLATES = [
    # a minimal template to get started with
    ('base.html', 'Base template'),
    ('minimal.html', 'Minimal template'),
    ('bootstrap5.html', 'Bootstrap5 template'),

]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGIN_URL = '/system/login/'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGES = [
    ('ru-Ru', 'Russia'),
    # ('en-us', 'English'),
]

LANGUAGE_CODE = 'ru-Ru'

TIME_ZONE = 'Europe/Moscow'
USE_I18N = True

USE_TZ = True

SITE_ID = 1

MEDIA_URL = 'media/'
MEDIA_ROOT = 'data/media/'

# setting.py
RATING_SETTINGS = {
    # generated urlhash length
    'URLHASH_LENGTH': 8
}
# FROM_ZERO = False  # if True, Rating will start from 0 otherwise 1
# RATES = 5  # 1, 3, 5, 10
# ICON  # path of rating icon
# HEIGHT = '2rem'  # Height of icon with unit


CMS_CONFIRM_VERSION4 = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'assets',
    # "/var/www/static/",
]

DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5.html"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


# DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = '587'
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'amiksoftstudio@gmail.com'
# EMAIL_HOST_PASSWORD = 'mpiindtituvkwakw'
# EMAIL_SERVER = EMAIL_HOST_USER
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# EMAIL_ADMIN = ['amikphoto@mail.ru']

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = '465'
# EMAIL_USE_TLS = True
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'amikphoto@yandex.ru'
EMAIL_HOST_PASSWORD = 'binguymtwghjdnjz'
EMAIL_SERVER = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = ['amikphoto@mail.ru']


DJANGORESIZED_DEFAULT_SIZE = [1920, 1080]
DJANGORESIZED_DEFAULT_SCALE = 1
DJANGORESIZED_DEFAULT_QUALITY = 75
DJANGORESIZED_DEFAULT_KEEP_META = True
DJANGORESIZED_DEFAULT_FORCE_FORMAT = 'JPEG'
DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {'JPEG': ".jpg"}
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = False


# from iommi import Style as IOMMIStyle
# from iommi.style_bootstrap import bootstrap


# IOMMI_DEFAULT_STYLE = IOMMIStyle(
#     bootstrap,
#     base_template='iommi_base.html',
    # root_assets=dict(
    # root_project_custom_css = Asset.css(attrs__href='/static/css/main.css'),
    # root_project_custom_js=Asset.js(attrs__href='/static/css/main.js'),
    # ),
# )

LOGIN_REQUIRED_FOR_CRUD = False
PERMISSION_REQUIRED_FOR_CRUD = False
PROJECT_NAME = 'foodster'

INTERNAL_IPS = [
    '127.0.0.1',
]
